title: CCAW
description: A Crash Course in Academic Writing
theme: just-the-docs

url: https://WoutDLN.github.io/CCAW

aux_links:
  Template Repository: https://github.com/WoutDLN/CCAW

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/img/seesaw.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/img/seesaw.ico"


# I tried to copy the GitHub Pages default settings as much as possible
# See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
callouts:
  highlight:
    color: purple
  best:
    title: Best Practice
    color: green
  good:
    title: Good Practice
    color: yellow
  bad: 
    title: Bad Practice
    color: red
  note:
    title: ⓘ Note
    color: blue
  disclaimer:
    title: ⚠ Disclaimer
    color: blue
  important:
    title: ⚠ Important
    color: yellow
  caution:
    title: 🛑 Caution
    color: red
  danger:
    title: 🛑 Danger
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-L9GM842G2V
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)